yolo_model:

  config_file:
    name: yolov3_custom.cfg
  weight_file:
    name: yolov3_custom_5000.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - red_circle
      - red_triangle
      - red_cross
      - blue_circle
      - blue_triangle
      - blue_cross
      - green_circle
      - green_triangle
      - green_cross

